name: GitHub Actions Pull Request

on:
  [push, pull_request]

env:
  LEIN_USE_BOOTCLASSPATH: no
  LEIN_ROOT: true
  LEIN_JVM_OPTS: "-Dmranderson.internal.no-parallelism=true -Dclojure.main.report=stderr"

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-18.04", "macOS-latest"]
        lein-version: ["2.9.4"]
        java-version: ["8", "11", "16"]
        integration-test-parallelism: ["1"]
    steps:
      - name: m2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: $${ runner.os }}-m2-${{ hashFiles('project.clj') }}
          restore-keys: $${ runner.os }}-m2-
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@fa522696baadfef7de0fe810135f446221e665c2
        with:
          cli: '1.10.3.1058'
          lein: ${{ matrix.lein-version }}
      # should match with `#'integration-test/lein`:
      - run: which lein
      - name: lint
        run: lein with-profile -user,+test,+eastwood eastwood
        env:
          no_eval_in_leiningen: true
      - name: run tests
        run: lein with-profile -user,-dev test
        env:
          no_eval_in_leiningen: true
      - name: exercise the plugin over a variety of real-world projects
        run: lein with-profile -user integration-test
        env:
          no_eval_in_leiningen: true
          integration_test_parallelism: ${{ matrix.integration-test-parallelism }}
